name: Release
on: workflow_dispatch

jobs:
  release-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: pip install "git+https://${{ secrets.SONAR_GITHUB_TOKEN }}@github.com/10gen/sonar.git@0.0.10"
#      - name: Login to Quay.io
#        uses: docker/login-action@v1
#        with:
#          registry: quay.io
#          username: ${{ secrets.QUAY_USERNAME }}
#          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - run: |
          released="$(scripts/ci/determine_required_releases.py mongodb-kubernetes-operator )"
          if [[ ${released}="unreleased" ]]; then
            python pipeline.py --image-name operator-ubi --release true
          fi
        env:
          MONGODB_COMMUNITY_CONFIG: "${{ env.GITHUB_WORKSPACE }}/scripts/ci/config.json"
